name: main-called
on:
  repository_dispatch:
    types: [panggilan]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Pull Subtree from Repository A
        uses: appleboy/ssh-action@master
        env:
          TREE_REPOSITORY: ${{ github.event.client_payload.tree_repository}}
          LINK_TREE_REPOSITORY: ${{ github.event.client_payload.link_tree_repository }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          envs: TREE_REPOSITORY, LINK_TREE_REPOSITORY
          script: |
            cd testing_git_team/main-caller
            git config user.email "fikrinursyahbani@gmail.com"
            git config user.name "mohammadfikrinursyahbani"

            git pull origin main

            if ls | grep $TREE_REPOSITORY
            then
              git subtree pull --prefix=$TREE_REPOSITORY $LINK_TREE_REPOSITORY main --squash
            else
              git subtree add --prefix=$TREE_REPOSITORY $LINK_TREE_REPOSITORY main --squash
            fi

            git push origin main
